-- Auto-generated by tools/build_injected_forbidden.py
-- Usage:
--   getgenv().__FORBIDDEN_BASE_URL = "https://raw.githubusercontent.com/gaston1799/RobloxLua/lua"
--   local AI = loadstring(game:HttpGet(getgenv().__FORBIDDEN_BASE_URL .. "/entry.lua"))()
--
-- If your executor does not preserve the chunk source for debug.info, set:
--   getgenv().__FORBIDDEN_BASE_URL = "https://raw.githubusercontent.com/gaston1799/RobloxLua/lua"
-- before loading entry.lua.

local GLOBAL_ENV = (getgenv and getgenv()) or _G
local ROOT_ENV = _G or GLOBAL_ENV or {}

local game = game or ROOT_ENV.game
local debug = debug or ROOT_ENV.debug
local string = string or ROOT_ENV.string
local table = table or ROOT_ENV.table
local type = type or ROOT_ENV.type
local typeof = typeof or ROOT_ENV.typeof
local ipairs = ipairs or ROOT_ENV.ipairs
local pairs = pairs or ROOT_ENV.pairs
local pcall = pcall or ROOT_ENV.pcall
local require = require or ROOT_ENV.require
local loadstring = loadstring or ROOT_ENV.loadstring
local setmetatable = setmetatable or ROOT_ENV.setmetatable
local getmetatable = getmetatable or ROOT_ENV.getmetatable
local error = error or ROOT_ENV.error
local tostring = tostring or ROOT_ENV.tostring

local function readInjectedBase()
    local candidates = {
        GLOBAL_ENV and GLOBAL_ENV.__FORBIDDEN_BASE_URL,
        _G and _G.__FORBIDDEN_BASE_URL,
    }

    for _, candidate in ipairs(candidates) do
        if type(candidate) == "string" and candidate ~= "" then
            return (candidate:gsub("/+$", ""))
        end
    end

    return nil
end

local function inferBaseUrl()
    local injectedBase = readInjectedBase()
    if injectedBase then
        return injectedBase
    end

    local debugTable = debug
    if type(debugTable) == "table" and type(debugTable.info) == "function" then
        local ok, source = pcall(function()
            return debugTable.info(1, "s")
        end)
        if ok and type(source) == "string" then
            source = source:gsub("^@", "")
            if source:match("^https?://") then
                local base = source:match("^(.*)/[^/]+$")
                if base then
                    return base
                end
            end
        end
    end

    error("Unable to infer Forbidden base URL. Set __FORBIDDEN_BASE_URL before loading entry.lua.", 0)
end

local BASE_URL = inferBaseUrl()
-- libs/forbidden lives inside the RobloxLua repo; relPaths are repo-root-relative.
BASE_URL = (BASE_URL:gsub("/libs/forbidden%$", ""))

local NODE_CLASSES = {
    ["libs/forbidden"] = "ModuleScript",
    ["libs/forbidden/AI"] = "ModuleScript",
    ["libs/forbidden/AI/Assist"] = "Folder",
    ["libs/forbidden/AI/Assist/DetectBadPaths"] = "ModuleScript",
    ["libs/forbidden/AI/Assist/PathfindDistanceHelper"] = "ModuleScript",
    ["libs/forbidden/AI/CommonMathRequests"] = "ModuleScript",
    ["libs/forbidden/AI/ConfigHandler"] = "ModuleScript",
    ["libs/forbidden/AI/ConfigHandler/Defaults"] = "ModuleScript",
    ["libs/forbidden/AI/Debugging"] = "ModuleScript",
    ["libs/forbidden/AI/DirectMoveTo"] = "ModuleScript",
    ["libs/forbidden/AI/MessageQueue"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor/States"] = "Folder",
    ["libs/forbidden/AI/PathfindingProcessor/States/Idle"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor/States/Pathing"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor/States/Tracking"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor/TriggerCleanup"] = "ModuleScript",
    ["libs/forbidden/AI/PathfindingProcessor/WaypointLooper"] = "ModuleScript",
    ["libs/forbidden/AI/PositionalOptimization"] = "ModuleScript",
    ["libs/forbidden/AI/Preprogrammed - Delete Me"] = "Script",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions"] = "Folder",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - SimpleTRACK"] = "Folder",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - SimpleTRACK/README"] = "Script",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY"] = "ModuleScript",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER"] = "ModuleScript",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS"] = "ModuleScript",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT"] = "ModuleScript",
    ["libs/forbidden/AI/RetrackingOptimization"] = "ModuleScript",
    ["libs/forbidden/AI/Types"] = "ModuleScript",
    ["libs/forbidden/AI/Types/TConfig"] = "ModuleScript",
    ["libs/forbidden/AI/Types/TRequestPriority"] = "ModuleScript",
    ["libs/forbidden/AI/Visualization"] = "Folder",
    ["libs/forbidden/AI/Visualization/WaypointsVisualization"] = "ModuleScript",
    ["libs/forbidden/AI/antilag"] = "Script",
    ["libs/forbidden/AI/info"] = "Script",
    ["libs/forbidden/Common"] = "ModuleScript",
    ["libs/forbidden/Common/Storage"] = "ModuleScript",
    ["libs/forbidden/Common/TypeHelp"] = "ModuleScript",
    ["libs/forbidden/DeveloperProductHandler"] = "Folder",
    ["libs/forbidden/DeveloperProductHandler/ExampleUIScript"] = "Folder",
    ["libs/forbidden/DeveloperProductHandler/ExampleUIScript/MPSHandler"] = "LocalScript",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService"] = "Folder",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products"] = "Folder",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/DevProductHandler"] = "Script",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase"] = "ModuleScript",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config"] = "ModuleScript",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl"] = "Folder",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example"] = "ModuleScript",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config"] = "ModuleScript",
    ["libs/forbidden/Libraries"] = "Folder",
    ["libs/forbidden/Libraries/Tables"] = "ModuleScript",
    ["libs/forbidden/Math"] = "ModuleScript",
    ["libs/forbidden/Math/CommonMathCollection"] = "ModuleScript",
    ["libs/forbidden/Math/MathVisualization"] = "ModuleScript",
    ["libs/forbidden/Math/old"] = "ModuleScript",
    ["libs/forbidden/Packages"] = "Folder",
    ["libs/forbidden/Packages/_Index"] = "Folder",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7"] = "Folder",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes"] = "Folder",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions"] = "Folder",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor"] = "Folder",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal"] = "ModuleScript",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove"] = "ModuleScript",
    ["libs/forbidden/Packages/robloxstatemachine"] = "ModuleScript"
}

local MODULE_PATHS = {
    ["libs/forbidden"] = "libs/forbidden/__module.lua",
    ["libs/forbidden/AI"] = "libs/forbidden/AI/__module.lua",
    ["libs/forbidden/AI/Assist/DetectBadPaths"] = "libs/forbidden/AI/Assist/DetectBadPaths/__module.lua",
    ["libs/forbidden/AI/Assist/PathfindDistanceHelper"] = "libs/forbidden/AI/Assist/PathfindDistanceHelper/__module.lua",
    ["libs/forbidden/AI/CommonMathRequests"] = "libs/forbidden/AI/CommonMathRequests/__module.lua",
    ["libs/forbidden/AI/ConfigHandler"] = "libs/forbidden/AI/ConfigHandler/__module.lua",
    ["libs/forbidden/AI/ConfigHandler/Defaults"] = "libs/forbidden/AI/ConfigHandler/Defaults/__module.lua",
    ["libs/forbidden/AI/Debugging"] = "libs/forbidden/AI/Debugging/__module.lua",
    ["libs/forbidden/AI/DirectMoveTo"] = "libs/forbidden/AI/DirectMoveTo/__module.lua",
    ["libs/forbidden/AI/MessageQueue"] = "libs/forbidden/AI/MessageQueue/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor"] = "libs/forbidden/AI/PathfindingProcessor/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor/States/Idle"] = "libs/forbidden/AI/PathfindingProcessor/States/Idle/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor/States/Pathing"] = "libs/forbidden/AI/PathfindingProcessor/States/Pathing/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor/States/Tracking"] = "libs/forbidden/AI/PathfindingProcessor/States/Tracking/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor/TriggerCleanup"] = "libs/forbidden/AI/PathfindingProcessor/TriggerCleanup/__module.lua",
    ["libs/forbidden/AI/PathfindingProcessor/WaypointLooper"] = "libs/forbidden/AI/PathfindingProcessor/WaypointLooper/__module.lua",
    ["libs/forbidden/AI/PositionalOptimization"] = "libs/forbidden/AI/PositionalOptimization/__module.lua",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY"] = "libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY/__module.lua",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER"] = "libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER/__module.lua",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS"] = "libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS/__module.lua",
    ["libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT"] = "libs/forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT/__module.lua",
    ["libs/forbidden/AI/RetrackingOptimization"] = "libs/forbidden/AI/RetrackingOptimization/__module.lua",
    ["libs/forbidden/AI/Types"] = "libs/forbidden/AI/Types/__module.lua",
    ["libs/forbidden/AI/Types/TConfig"] = "libs/forbidden/AI/Types/TConfig/__module.lua",
    ["libs/forbidden/AI/Types/TRequestPriority"] = "libs/forbidden/AI/Types/TRequestPriority/__module.lua",
    ["libs/forbidden/AI/Visualization/WaypointsVisualization"] = "libs/forbidden/AI/Visualization/WaypointsVisualization/__module.lua",
    ["libs/forbidden/Common"] = "libs/forbidden/Common/__module.lua",
    ["libs/forbidden/Common/Storage"] = "libs/forbidden/Common/Storage/__module.lua",
    ["libs/forbidden/Common/TypeHelp"] = "libs/forbidden/Common/TypeHelp/__module.lua",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase"] = "libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/__module.lua",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config"] = "libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config/__module.lua",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example"] = "libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/__module.lua",
    ["libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config"] = "libs/forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config/__module.lua",
    ["libs/forbidden/Libraries/Tables"] = "libs/forbidden/Libraries/Tables/__module.lua",
    ["libs/forbidden/Math"] = "libs/forbidden/Math/__module.lua",
    ["libs/forbidden/Math/CommonMathCollection"] = "libs/forbidden/Math/CommonMathCollection/__module.lua",
    ["libs/forbidden/Math/MathVisualization"] = "libs/forbidden/Math/MathVisualization/__module.lua",
    ["libs/forbidden/Math/old"] = "libs/forbidden/Math/old/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal/__module.lua",
    ["libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove"] = "libs/forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove/__module.lua",
    ["libs/forbidden/Packages/robloxstatemachine"] = "libs/forbidden/Packages/robloxstatemachine/__module.lua"
}

local NODE_METHODS = {}
local NODE_MT = {
    __index = function(self, key)
        local method = NODE_METHODS[key]
        if method ~= nil then
            return method
        end

        return self._children[key]
    end,
}

local nodes = {}

local function splitId(id)
    local parts = {}
    for part in string.gmatch(id, "[^/]+") do
        table.insert(parts, part)
    end
    return parts
end

local function ensureNode(id)
    local existing = nodes[id]
    if existing then
        return existing
    end

    local parts = splitId(id)
    local name = parts[#parts]
    local parentId = id:match("^(.*)/[^/]+$")
    local parentNode = nil
    if parentId then
        parentNode = ensureNode(parentId)
    end

    local node = setmetatable({
        _forbiddenNode = true,
        _id = id,
        _children = {},
        Name = name,
        ClassName = NODE_CLASSES[id] or "Folder",
        Parent = parentNode,
    }, NODE_MT)

    nodes[id] = node

    if parentNode then
        parentNode._children[name] = node
    end

    return node
end

for id, _ in pairs(NODE_CLASSES) do
    ensureNode(id)
end

function NODE_METHODS:GetChildren()
    local children = {}
    for _, child in pairs(self._children) do
        table.insert(children, child)
    end

    table.sort(children, function(a, b)
        return a.Name < b.Name
    end)

    return children
end

function NODE_METHODS:GetDescendants()
    local descendants = {}

    local function walk(node)
        for _, child in ipairs(node:GetChildren()) do
            table.insert(descendants, child)
            walk(child)
        end
    end

    walk(self)
    return descendants
end

function NODE_METHODS:FindFirstChild(name, recursive)
    local direct = self._children[name]
    if direct then
        return direct
    end

    if recursive then
        for _, child in ipairs(self:GetChildren()) do
            local found = child:FindFirstChild(name, true)
            if found then
                return found
            end
        end
    end

    return nil
end

function NODE_METHODS:WaitForChild(name, timeout)
    local found = self:FindFirstChild(name, false)
    if found then
        return found
    end

    error(("Synthetic node %s has no child named %s"):format(self:GetFullName(), tostring(name)), 2)
end

function NODE_METHODS:IsA(className)
    return self.ClassName == className
end

function NODE_METHODS:GetFullName()
    local parts = {}
    local current = self
    while current do
        table.insert(parts, 1, current.Name)
        current = current.Parent
    end
    return table.concat(parts, ".")
end

function NODE_METHODS:Destroy()
    if self.Parent then
        self.Parent._children[self.Name] = nil
    end
    nodes[self._id] = nil
end

local runtime = {}
local moduleCache = {}
local loading = {}
runtime.globals = ROOT_ENV

function runtime:getNode(id)
    local node = nodes[id]
    if not node then
        error("Unknown Forbidden synthetic node: " .. tostring(id), 2)
    end
    return node
end

local function encodeUrlPath(path)
    return (path:gsub("([^%%w%%-%%._~/@])", function(char)
        return string.format("%%%02X", string.byte(char))
    end))
end

    local function syntheticRequire(target)
        if typeof(target) == "Instance" then
            return require(target)
        end

    if type(target) ~= "table" or not target._forbiddenNode then
        error("Forbidden synthetic require expected a synthetic node or Instance.", 2)
    end

    if target.ClassName ~= "ModuleScript" then
        error("Attempted to require non-ModuleScript synthetic node: " .. target:GetFullName(), 2)
    end

    local moduleId = target._id
    if moduleCache[moduleId] ~= nil then
        return moduleCache[moduleId]
    end

    if loading[moduleId] then
        error("Circular synthetic require detected for " .. moduleId, 2)
    end

    local relPath = MODULE_PATHS[moduleId]
    if not relPath then
        error("No remote module path registered for " .. moduleId, 2)
    end

    loading[moduleId] = true

    local url = BASE_URL .. "/" .. encodeUrlPath(relPath)
    local source = game:HttpGet(url)
    local prelude = [[
local script, require, runtime = ...
local remoteRequire = runtime.remoteRequire
local __FORBIDDEN_ROOT = runtime:getNode('libs/forbidden')
local _G = runtime.globals
local game = game or _G.game
local workspace = workspace or _G.workspace
local Enum = Enum or _G.Enum
local task = task or _G.task
local os = os or _G.os
local math = math or _G.math
local string = string or _G.string
local table = table or _G.table
local type = type or _G.type
local typeof = typeof or _G.typeof
local ipairs = ipairs or _G.ipairs
local pairs = pairs or _G.pairs
local next = next or _G.next
local tonumber = tonumber or _G.tonumber
local tostring = tostring or _G.tostring
local pcall = pcall or _G.pcall
local xpcall = xpcall or _G.xpcall
local assert = assert or _G.assert
local error = error or _G.error
local warn = warn or _G.warn
local setmetatable = setmetatable or _G.setmetatable
local getmetatable = getmetatable or _G.getmetatable
local rawget = rawget or _G.rawget
local rawset = rawset or _G.rawset
local select = select or _G.select
local unpack = unpack or (_G.table and _G.table.unpack) or _G.unpack
local Vector2 = Vector2 or _G.Vector2
local Vector3 = Vector3 or _G.Vector3
local CFrame = CFrame or _G.CFrame
local Color3 = Color3 or _G.Color3
local UDim2 = UDim2 or _G.UDim2
local RaycastParams = RaycastParams or _G.RaycastParams
local PathWaypoint = PathWaypoint or _G.PathWaypoint
]]
    local chunk, loadErr = loadstring(prelude .. source)
    if not chunk then
        loading[moduleId] = nil
        error(loadErr, 0)
    end

    local ok, result = pcall(chunk, target, syntheticRequire, runtime)
    loading[moduleId] = nil
    if not ok then
        error(result, 0)
    end

    if result == nil then
        result = true
    end

    moduleCache[moduleId] = result
    return result
    end

    runtime.require = syntheticRequire
    runtime.remoteRequire = function(target)
        if type(target) == "string" then
            target = runtime:getNode(target)
        end
        return syntheticRequire(target)
    end
    GLOBAL_ENV.__FORBIDDEN_LAST_RUNTIME = runtime

    return syntheticRequire(runtime:getNode("libs/forbidden/AI"))
